

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace uyg04.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DB03Entities : DbContext
{
    public DB03Entities()
        : base("name=DB03Entities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Arac> Arac { get; set; }

    public virtual DbSet<Kategori> Kategori { get; set; }

    public virtual DbSet<Kayit> Kayit { get; set; }

}

}

